#!/usr/bin/env python3
"""Rebuild every public artifact from the curve registry.

Usage from repository root:
    python scripts/build_all.py

Single source of truth:
    curve_specs/curves.yaml   curve definitions / model parameters
    curve_specs/sources.yaml  public source metadata
    scripts/curve_models.py   mathematical model families

Outputs regenerated by this script:
    data/*.csv
    assets/figures/**/*.svg + *.png
    generated/*.qmd
    references.bib
    compare.html
    downloads/log-gamma-derivatives-contact-sheet.pdf
    index.html
    FILES.txt
"""
from __future__ import annotations

import html
import json
import math
import re
import shutil
import subprocess
import sys
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = ROOT / "scripts"
sys.path.insert(0, str(SCRIPTS))
import curve_models as cm

REGISTRY, SOURCES = cm.load_registry(ROOT)
CURVES = REGISTRY["curves"]
CONFIG = REGISTRY["comparison"]
CAMERAS = [c for c in CURVES if c["family"] == "camera"]
REFERENCES = [c for c in CURVES if c["family"] == "reference"]
GRAY = float(CONFIG.get("gray_reference", 0.18))

FIG_OV = ROOT / "assets" / "figures" / "overview"
FIG_IND = ROOT / "assets" / "figures" / "individual"
FIG_JUN = ROOT / "assets" / "figures" / "junction"
DATA = ROOT / "data"
GENERATED = ROOT / "generated"
DOWNLOADS = ROOT / "downloads"
for d in (FIG_OV, FIG_IND, FIG_JUN, DATA, GENERATED, DOWNLOADS):
    d.mkdir(parents=True, exist_ok=True)

plt.rcParams["svg.fonttype"] = "none"


def clean_generated_assets():
    for d in (FIG_OV, FIG_IND, FIG_JUN):
        for p in d.glob("*"):
            if p.is_file() and p.suffix.lower() in {".svg", ".png"}:
                p.unlink()
    for p in GENERATED.glob("*"):
        if p.is_file():
            p.unlink()


def source_citation(c):
    return "; ".join("@" + key for key in c.get("sources", []))


def markdown_table(headers, rows, aligns=None):
    def esc(v):
        return str(v).replace("|", "\\|").replace("\n", " ")
    lines = ["| " + " | ".join(esc(h) for h in headers) + " |"]
    if aligns is None:
        aligns = ["---"] * len(headers)
    lines.append("| " + " | ".join(aligns) + " |")
    for row in rows:
        lines.append("| " + " | ".join(esc(v) for v in row) + " |")
    return "\n".join(lines) + "\n"


def fmt_num(x, digits=6):
    if x is None or not np.isfinite(x):
        return ""
    if abs(x) >= 1e4 or (abs(x) > 0 and abs(x) < 1e-5):
        return f"{x:.3e}"
    return f"{x:.{digits}g}"


def generate_bib():
    blocks = []
    for key, s in SOURCES.items():
        typ = s.get("type", "techreport")
        entry = "misc" if typ == "misc" else "techreport"
        author = s.get("author", s.get("organization", ""))
        if " and " in author:
            bib_author = "{" + author + "}"
        else:
            bib_author = "{{" + author + "}}"
        fields = [("author", bib_author), ("title", "{" + s["title"] + "}")]
        if entry == "techreport" and s.get("organization"):
            fields.append(("institution", "{" + s["organization"] + "}"))
        if s.get("year") is not None:
            fields.append(("year", str(s["year"])))
        if s.get("month"):
            fields.append(("month", "{" + str(s["month"]) + "}"))
        if s.get("url"):
            fields.append(("url", "{" + s["url"] + "}"))
        if s.get("note"):
            fields.append(("note", "{" + s["note"] + "}"))
        lines = [f"@{entry}{{{key},"]
        for i, (k, v) in enumerate(fields):
            comma = "," if i < len(fields) - 1 else ""
            lines.append(f"  {k:<11} = {v}{comma}")
        lines.append("}")
        blocks.append("\n".join(lines))
    (ROOT / "references.bib").write_text("\n\n".join(blocks) + "\n", encoding="utf-8")


def generate_fragments(summary_df, junction_df):
    camera_lines = []
    for c in CAMERAS:
        cites = source_citation(c)
        camera_lines.append(f"- {c['name']} [{cites}]" if cites else f"- {c['name']}")
    (GENERATED / "camera_curves.qmd").write_text("\n".join(camera_lines) + "\n", encoding="utf-8")

    headers = ["Curve", "y(18%)", "1023×y", "1023×dy/dstop at 18%", "d²y/dstop² at 18%"]
    rows = []
    for _, r in summary_df.iterrows():
        rows.append([
            r["curve"], fmt_num(r["y_18pct"]), fmt_num(r["code_1023"]),
            fmt_num(r["code_per_stop_1023"]), fmt_num(r["d2_stop_18pct"]),
        ])
    (GENERATED / "summary_table.qmd").write_text(markdown_table(headers, rows, [":---", "---:", "---:", "---:", "---:"]), encoding="utf-8")

    headers = ["Curve", "Junction", "Join", "Domain", "Lower / left branch", "Upper / right branch", "C0", "C1", "C2"]
    rows = []
    for _, r in junction_df.iterrows():
        rows.append([
            r["curve"], r["junction_label"], fmt_num(r["join"], 7), r["domain"],
            r["lower_branch"], r["upper_branch"], r["C0"], r["C1"], r["C2"],
        ])
    # Smooth reference rows without a junction.
    for c in REFERENCES:
        if not c.get("junctions"):
            rows.append([c["name"], "—", "", "none", c["branches"]["low"], c["branches"]["high"],
                         "smooth/no piecewise join", "smooth/no piecewise join", "smooth/no piecewise join"])
    (GENERATED / "junction_table.qmd").write_text(markdown_table(headers, rows, [":---", ":---", "---:", ":---", ":---", ":---", ":---", ":---", ":---"]), encoding="utf-8")

    # Direct primary-source index, useful even when the article is used simply as a white-paper link collection.
    seen = set()
    source_rows = []
    for c in CAMERAS:
        for key in c.get("sources", []):
            if key in seen:
                continue
            seen.add(key)
            s = SOURCES[key]
            url = s.get("url")
            title = s["title"]
            link = f"[{title}]({url})" if url else title
            source_rows.append([s.get("organization", s.get("author", "")), link, str(s.get("year", ""))])
    (GENERATED / "primary_sources.qmd").write_text(
        markdown_table(["Organization", "Specification / white paper", "Year"], source_rows, [":---", ":---", "---:"]), encoding="utf-8")


def overview_data():
    rmin = float(CONFIG.get("scene_min", 1e-5))
    rmax = float(CONFIG.get("scene_max", 16.0))
    r = np.unique(np.r_[np.geomspace(rmin, 0.02, 900), np.geomspace(0.02, rmax, 1800)])
    stops = np.linspace(float(CONFIG.get("stop_min", -12.0)), float(CONFIG.get("stop_max", 10.0)), 1800)
    rs = GRAY * (2.0**stops)
    return r, stops, rs


def save_overview_plot(filename, domain, metric):
    r, stops, rs = overview_data()
    fig, ax = plt.subplots(figsize=(10, 6.5))
    for c in CAMERAS:
        if domain == "scene":
            x = r
            if metric == "y": y = cm.encode(c, r)
            elif metric == "d1": y = cm.d1(c, r)
            else: y = cm.d2(c, r)
        else:
            x = stops
            if metric == "y": y = cm.encode(c, rs)
            elif metric == "d1": y = cm.g1_stop(c, rs)
            else: y = cm.g2_stop(c, rs)
        ax.plot(x, y, label=c["name"])
    if domain == "scene":
        ax.set_xscale("log")
        ax.set_xlabel("Reflectance-like scene-linear input r (18% gray = 0.18)")
        if metric == "y":
            ax.set_ylabel("Normalized encoded output"); ax.set_title("Published camera log curves — common reflectance-like axis")
        elif metric == "d1":
            ax.set_yscale("log"); ax.set_ylabel("First derivative f'(r)"); ax.set_title("First derivative in scene-linear domain")
        else:
            ax.set_yscale("symlog", linthresh=1e-2); ax.set_ylabel("Second derivative f''(r)"); ax.set_title("Second derivative in scene-linear domain (symlog y-scale)")
    else:
        ax.set_xlabel("Stops from 18% gray")
        if metric == "y":
            ax.set_ylabel("Normalized encoded output"); ax.set_title("Published camera log curves — stop domain")
        elif metric == "d1":
            ax.set_ylabel("g'(s): normalized output per stop"); ax.set_title("Code allocation per stop")
        else:
            ax.set_ylabel("g''(s): change of allocation per stop²"); ax.set_title("Second derivative in stop domain")
    ax.grid(True, which="both", alpha=0.25)
    ax.legend(frameon=False, fontsize=7, ncol=3)
    fig.tight_layout()
    fig.savefig(FIG_OV / (filename + ".svg"))
    fig.savefig(FIG_OV / (filename + ".png"), dpi=180)
    plt.close(fig)


def save_reference_plots():
    lab = next(c for c in REFERENCES if c["model"] == "lab")
    cineon = next(c for c in REFERENCES if c["model"] == "cineon")
    j = cm.primary_junction(lab)["value"]
    x = np.linspace(j * 0.15, j * 2.0, 700)
    fig, ax = plt.subplots(figsize=(7.2, 4.2))
    ax.plot(x, cm.encode(lab, x)); ax.axvline(j, linestyle="--", linewidth=0.9)
    ax.set_xlabel("Y/Yn"); ax.set_ylabel("L* / 100"); ax.set_title("CIE L*: value near the piecewise join"); ax.grid(True, alpha=.25); fig.tight_layout()
    fig.savefig(FIG_OV / "lab_junction_value.svg"); fig.savefig(FIG_OV / "lab_junction_value.png", dpi=170); plt.close(fig)
    fig, ax = plt.subplots(figsize=(7.2, 4.2))
    ax.plot(x, cm.d1(lab, x)); ax.axvline(j, linestyle="--", linewidth=0.9)
    ax.set_xlabel("Y/Yn"); ax.set_ylabel("d(L*/100)/d(Y/Yn)"); ax.set_title("CIE L*: first derivative near the join"); ax.grid(True, alpha=.25); fig.tight_layout()
    fig.savefig(FIG_OV / "lab_junction_first_derivative.svg"); fig.savefig(FIG_OV / "lab_junction_first_derivative.png", dpi=170); plt.close(fig)

    r = np.geomspace(1e-5, 2.0, 1000)
    fig, ax = plt.subplots(figsize=(8.0, 4.8))
    ax.plot(r, cm.encode(lab, r), label=lab["name"])
    ax.plot(r, cm.encode(cineon, r), label=cineon["name"])
    ax.set_xscale("log"); ax.set_xlabel("Normalized / reflectance-like input"); ax.set_ylabel("Normalized output")
    ax.set_title("Reference functions: CIE L* and Cineon"); ax.grid(True, which="both", alpha=.25); ax.legend(frameon=False); fig.tight_layout()
    fig.savefig(FIG_OV / "reference_curves_lab_cineon.svg"); fig.savefig(FIG_OV / "reference_curves_lab_cineon.png", dpi=170); plt.close(fig)


def generate_tables():
    summary_rows = []
    for c in CAMERAS:
        y = float(cm.encode(c, GRAY))
        g1 = float(cm.g1_stop(c, GRAY))
        g2 = float(cm.g2_stop(c, GRAY))
        summary_rows.append({
            "curve_id": c["id"], "curve": c["name"], "y_18pct": y,
            "code_1023": 1023.0 * y, "dy_dr_18pct": float(cm.d1(c, GRAY)),
            "d2y_dr2_18pct": float(cm.d2(c, GRAY)),
            "dy_dstop_18pct": g1, "code_per_stop_1023": 1023.0 * g1,
            "d2_stop_18pct": g2,
        })
    summary_df = pd.DataFrame(summary_rows)
    summary_df.to_csv(DATA / "summary_at_18pct.csv", index=False)

    junction_rows = []
    for c in CURVES:
        for j in c.get("junctions", []):
            m = cm.junction_metrics(c, j)
            c0, c1, c2 = cm.continuity_label(m["value_jump_high_minus_low"], m["slope_jump_high_minus_low"], m["second_derivative_jump_high_minus_low"])
            junction_rows.append({
                "curve_id": c["id"], "curve": c["name"], "junction_id": j["id"], "junction_label": j.get("label", j["id"]),
                "join": m["join"], "domain": j.get("domain", "r"),
                "lower_branch": j.get("left_branch", c["branches"]["low"]), "upper_branch": j.get("right_branch", c["branches"]["high"]),
                "value_jump": m["value_jump_high_minus_low"], "slope_jump": m["slope_jump_high_minus_low"],
                "second_derivative_jump": m["second_derivative_jump_high_minus_low"], "C0": c0, "C1": c1, "C2": c2,
            })
    junction_df = pd.DataFrame(junction_rows)
    junction_df.to_csv(DATA / "junction_continuity.csv", index=False)

    r, stops, rs = overview_data()
    scene_frames = []
    stop_frames = []
    for c in CAMERAS:
        scene_frames.append(pd.DataFrame({
            "curve_id": c["id"], "curve": c["name"], "r": r,
            "encoded": cm.encode(c, r), "d1": cm.d1(c, r), "d2": cm.d2(c, r),
        }))
        stop_frames.append(pd.DataFrame({
            "curve_id": c["id"], "curve": c["name"], "stops_from_18pct": stops, "r": rs,
            "encoded": cm.encode(c, rs), "d1_stop": cm.g1_stop(c, rs), "d2_stop": cm.g2_stop(c, rs),
        }))
    pd.concat(scene_frames, ignore_index=True).to_csv(DATA / "sampled_camera_curves.csv", index=False)
    pd.concat(stop_frames, ignore_index=True).to_csv(DATA / "sampled_camera_curves_stops.csv", index=False)
    return summary_df, junction_df


def junction_range(c, j):
    x = float(j["value"])
    ax = abs(x)
    if ax < 1e-12: span = 0.035
    elif ax < 0.002: span = max(ax * 0.85, 0.0007)
    elif ax < 0.05: span = max(ax * 0.7, 0.008)
    else: span = ax * 0.55
    lo, hi = x - span, x + span
    if c["model"] == "logc4":
        safe_lo = -64.0 / c["params"]["a"] + 1e-8
        lo = max(lo, safe_lo)
    if c["model"] == "nlog":
        lo = max(lo, -0.00749)
    return lo, hi


def make_junction_triptych(c, j, out_svg, out_png=None, compact=False):
    lo, hi = junction_range(c, j)
    x = np.linspace(lo, hi, 700)
    join = float(j["value"])
    fig, axes = plt.subplots(1, 3, figsize=(9.3, 2.8) if compact else (10.5, 3.2))
    funcs = [cm.encode, cm.d1, cm.d2]
    titles = ["value", "first derivative", "second derivative"]
    ylabs = ["f(r)", "f'(r)", "f''(r)"]
    for ax, fun, title, yl in zip(axes, funcs, titles, ylabs):
        ax.plot(x, fun(c, x), linewidth=1.5)
        ax.axvline(join, linestyle="--", linewidth=.9)
        ax.set_title(title, fontsize=9); ax.set_xlabel("r", fontsize=8); ax.set_ylabel(yl, fontsize=8)
        ax.tick_params(labelsize=7); ax.grid(True, alpha=.22)
    fig.suptitle(f"{c['name']} — {j.get('label', j['id'])} at {join:.6g}", fontsize=11, y=1.01)
    fig.tight_layout()
    fig.savefig(out_svg, bbox_inches="tight")
    if out_png:
        fig.savefig(out_png, dpi=170, bbox_inches="tight")
    plt.close(fig)


def svg_inner(path):
    txt = Path(path).read_text(encoding="utf-8")
    m = re.search(r"(<svg[\s\S]*</svg>)", txt)
    return m.group(1) if m else txt


def build_interactive():
    r, stops, rs = overview_data()
    # Keep colors from Matplotlib's default cycle; the checkbox swatches mirror those assigned colors.
    color_cycle = plt.rcParams["axes.prop_cycle"].by_key().get("color", [])
    curve_color = {c["id"]: color_cycle[i % len(color_cycle)] if color_cycle else None for i, c in enumerate(CAMERAS)}

    specs = [
        ("interactive_scene_curve.svg", "scene", "y"), ("interactive_scene_d1.svg", "scene", "d1"), ("interactive_scene_d2.svg", "scene", "d2"),
        ("interactive_stop_curve.svg", "stop", "y"), ("interactive_stop_d1.svg", "stop", "d1"), ("interactive_stop_d2.svg", "stop", "d2"),
    ]
    for fn, domain, metric in specs:
        fig, ax = plt.subplots(figsize=(7.2, 4.4))
        for c in CAMERAS:
            if domain == "scene":
                x = r
                y = cm.encode(c, r) if metric == "y" else (cm.d1(c, r) if metric == "d1" else cm.d2(c, r))
            else:
                x = stops
                y = cm.encode(c, rs) if metric == "y" else (cm.g1_stop(c, rs) if metric == "d1" else cm.g2_stop(c, rs))
            kwargs = {"linewidth": 1.25}
            if curve_color[c["id"]]: kwargs["color"] = curve_color[c["id"]]
            line, = ax.plot(x, y, **kwargs)
            line.set_gid("curve-" + c["id"])
        if domain == "scene":
            ax.set_xscale("log"); ax.set_xlabel("r")
            if metric == "y": ax.set_ylabel("encoded output"); ax.set_title("Scene-linear: curve")
            elif metric == "d1": ax.set_yscale("log"); ax.set_ylabel("f'(r)"); ax.set_title("Scene-linear: first derivative")
            else: ax.set_yscale("symlog", linthresh=1e-2); ax.set_ylabel("f''(r)"); ax.set_title("Scene-linear: second derivative")
        else:
            ax.set_xlabel("Stops from 18% gray")
            if metric == "y": ax.set_ylabel("encoded output"); ax.set_title("Stop domain: curve")
            elif metric == "d1": ax.set_ylabel("g'(s) / stop"); ax.set_title("Stop domain: allocation per stop")
            else: ax.set_ylabel("g''(s) / stop²"); ax.set_title("Stop domain: second derivative")
        ax.grid(True, which="both", alpha=.22); fig.tight_layout(); fig.savefig(GENERATED / fn); plt.close(fig)

    junction_cards = []
    for c in CAMERAS:
        for j in c.get("junctions", []):
            asset_name = f"junction_{c['id']}_{j['id']}"
            svg = FIG_JUN / f"{asset_name}.svg"
            png = None
            make_junction_triptych(c, j, svg, png, compact=True)
            m = cm.junction_metrics(c, j)
            c0, c1, c2 = cm.continuity_label(m["value_jump_high_minus_low"], m["slope_jump_high_minus_low"], m["second_derivative_jump_high_minus_low"])
            junction_cards.append(
                f'<article class="junction-card" data-slug="{c["id"]}" hidden>'
                f'<div class="junction-head"><strong>{html.escape(c["name"])} — {html.escape(j.get("label", j["id"]))}</strong>'
                f'<span>C0: {html.escape(c0)} / C1: {html.escape(c1)} / C2: {html.escape(c2)}</span></div>'
                f'{svg_inner(svg)}</article>'
            )

    checkboxes = []
    for c in CAMERAS:
        color = curve_color[c["id"]] or "currentColor"
        checkboxes.append(
            f'<label class="curve-option"><input type="checkbox" value="{c["id"]}">'
            f'<span class="swatch" style="background:{color}"></span>{html.escape(c["name"])}</label>'
        )
    plot_blocks = [f'<div class="plot-card">{svg_inner(GENERATED / fn)}</div>' for fn, _, _ in specs]

    out = f'''<!doctype html>
<html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Log curve interactive comparison</title>
<style>
:root{{--bg:#fff;--fg:#171717;--muted:#777}} *{{box-sizing:border-box}} body{{margin:0;font-family:system-ui,-apple-system,"Noto Sans JP",sans-serif;color:var(--fg);background:var(--bg)}}
.wrap{{max-width:1500px;margin:0 auto;padding:18px}} .intro{{font-size:14px;color:#444;margin:0 0 12px}}
.controls{{display:flex;flex-wrap:wrap;gap:7px 14px;border:1px solid #ddd;border-radius:8px;padding:12px;background:#fafafa;position:sticky;top:0;z-index:20}}
.curve-option{{display:flex;align-items:center;gap:5px;font-size:13px;white-space:nowrap;cursor:pointer}} .curve-option input{{margin:0}} .swatch{{width:12px;height:3px;display:inline-block;border-radius:2px}}
.grid{{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin-top:14px}} .plot-card{{border:1px solid #ddd;border-radius:8px;padding:4px;background:#fff;overflow:hidden}} .plot-card svg{{display:block;width:100%;height:auto}}
g[id^="curve-"] path{{transition:opacity .14s,stroke-width .14s,stroke .14s}} g.curve-muted path{{stroke:#b9b9b9 !important;stroke-width:.65px !important;opacity:.24 !important}} g.curve-selected path{{stroke-width:2.65px !important;opacity:1 !important}}
.junction-section{{margin-top:24px;border-top:1px solid #ddd;padding-top:16px}} .junction-note{{font-size:13px;color:#555}} .junction-grid{{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}}
.junction-card{{border:1px solid #ddd;border-radius:8px;padding:8px;background:#fff}} .junction-card svg{{width:100%;height:auto;display:block}} .junction-head{{display:flex;justify-content:space-between;gap:12px;align-items:baseline;font-size:12px;margin-bottom:4px}} .junction-head strong{{font-size:14px}} .empty-note{{padding:18px;border:1px dashed #bbb;border-radius:8px;color:#666;text-align:center}}
@media (max-width:1050px){{.grid,.junction-grid{{grid-template-columns:repeat(2,minmax(0,1fr))}}}} @media (max-width:680px){{.grid,.junction-grid{{grid-template-columns:1fr}} .controls{{position:static}}}}
</style></head><body><div class="wrap">
<p class="intro">チェックしたカーブを6枚の図で同時にハイライトします。未選択時は全体図として表示し、選択時は非選択カーブを薄くします。複数の接続点を持つ関数では、選択すると各接続点の拡大図が表示されます。</p>
<div class="controls">{''.join(checkboxes)}</div><div class="grid">{''.join(plot_blocks)}</div>
<section class="junction-section"><h2>接続点の拡大</h2><p class="junction-note">value / 1階微分 / 2階微分を同じチェック状態で確認できます。</p><div id="junction-empty" class="empty-note">上のチェックボックスでカーブを選択してください。</div><div class="junction-grid">{''.join(junction_cards)}</div></section>
</div><script>
const boxes=[...document.querySelectorAll('.curve-option input')]; function update(){{const selected=new Set(boxes.filter(b=>b.checked).map(b=>b.value)); const active=selected.size>0; document.querySelectorAll('g[id^="curve-"]').forEach(g=>{{const slug=g.id.replace(/^curve-/, '');g.classList.toggle('curve-muted',active&&!selected.has(slug));g.classList.toggle('curve-selected',active&&selected.has(slug));}}); document.querySelectorAll('.junction-card').forEach(card=>{{card.hidden=!selected.has(card.dataset.slug)}}); document.getElementById('junction-empty').hidden=active;}} boxes.forEach(b=>b.addEventListener('change',update)); update();
</script></body></html>'''
    (ROOT / "compare.html").write_text(out, encoding="utf-8")
    for fn, _, _ in specs:
        (GENERATED / fn).unlink(missing_ok=True)


def make_individual_assets():
    r = np.unique(np.r_[np.geomspace(float(CONFIG.get("scene_min", 1e-5)), 0.02, 320), np.geomspace(0.02, float(CONFIG.get("scene_max", 16.0)), 520)])
    all_d2 = np.concatenate([cm.d2(c, r) for c in CAMERAS])
    finite = all_d2[np.isfinite(all_d2)]
    d2_lim = max(np.percentile(np.abs(finite), 99.8), 1.0)
    assets = {}
    for c in CAMERAS:
        fig, axes = plt.subplots(2, 3, figsize=(12.8, 7.2))
        funcs = [cm.encode, cm.d1, cm.d2]
        titles = ["curve f(r)", "first derivative f'(r)", "second derivative f''(r)"]
        for ax, fun, title, ys in zip(axes[0], funcs, titles, ["linear", "log", "symlog"]):
            ax.plot(r, fun(c, r), linewidth=1.4); ax.set_xscale("log")
            if ys == "log": ax.set_yscale("log")
            if ys == "symlog": ax.set_yscale("symlog", linthresh=1e-2); ax.set_ylim(-d2_lim, d2_lim)
            pj = cm.primary_junction(c)
            if pj and float(pj["value"]) > 0: ax.axvline(float(pj["value"]), linestyle="--", linewidth=.8)
            ax.set_title(title, fontsize=10); ax.set_xlabel("r", fontsize=8); ax.tick_params(labelsize=7); ax.grid(True, which="both", alpha=.2)
        pj = cm.primary_junction(c)
        if pj:
            lo, hi = junction_range(c, pj); xj = np.linspace(lo, hi, 650); jv = float(pj["value"])
            for ax, fun, title in zip(axes[1], funcs, ["primary junction: value", "primary junction: first derivative", "primary junction: second derivative"]):
                ax.plot(xj, fun(c, xj), linewidth=1.4); ax.axvline(jv, linestyle="--", linewidth=.8)
                ax.set_title(title, fontsize=10); ax.set_xlabel("r", fontsize=8); ax.tick_params(labelsize=7); ax.grid(True, alpha=.2)
        else:
            for ax in axes[1]: ax.axis("off")
        fig.suptitle(c["name"], fontsize=15, y=.985)
        fig.text(.5, .012, "Published-formula implementation; source keys: " + ", ".join(c.get("sources", [])), ha="center", fontsize=8)
        fig.tight_layout(rect=[0, .03, 1, .96])
        png = FIG_IND / f"individual_{c['id']}.png"
        fig.savefig(png, dpi=120); plt.close(fig); assets[c["id"]] = png
    return assets


def build_pdf(individual_assets):
    from reportlab.pdfgen import canvas
    from reportlab.lib.pagesizes import A4, landscape
    from reportlab.lib.utils import ImageReader
    from reportlab.pdfbase.cidfonts import UnicodeCIDFont
    from reportlab.pdfbase import pdfmetrics
    from reportlab.lib.colors import HexColor

    try:
        pdfmetrics.registerFont(UnicodeCIDFont("HeiseiKakuGo-W5")); font = "HeiseiKakuGo-W5"
    except Exception:
        font = "Helvetica"
    page_size = landscape(A4); pw, ph = page_size
    pdf_path = DOWNLOADS / "log-gamma-derivatives-contact-sheet.pdf"
    cpdf = canvas.Canvas(str(pdf_path), pagesize=page_size)
    def header(title, subtitle=None):
        cpdf.setFont(font, 17); cpdf.drawString(28, ph-30, title)
        if subtitle:
            cpdf.setFont(font, 8.5); cpdf.setFillColor(HexColor("#555555")); cpdf.drawString(28, ph-44, subtitle); cpdf.setFillColor(HexColor("#000000"))
    def page_no(n): cpdf.setFont(font, 7.5); cpdf.setFillColor(HexColor("#777777")); cpdf.drawRightString(pw-24, 15, str(n)); cpdf.setFillColor(HexColor("#000000"))
    page = 1
    header("公開仕様から見るLogカーブ - 静的図版", "微分・2階微分・接続条件 / メーカー公開文書の式を再実装した比較")
    txt = cpdf.beginText(34, ph-78); txt.setLeading(16); txt.setFont(font, 10.2)
    for line in [
        "このPDFは、インタラクティブHTMLとは別系統の静的図版です。",
        "全体図の後に、各カーブの個別コンタクトシートを収録しています。",
        "",
        "留保：本資料は各社の仕様書・データシート・ホワイトペーパーに記載された公開数式の再実装です。",
        "実機測定によるOETF推定ではなく、内部画像処理、センサー固有処理、EI依存処理、量子化、クリップ等を",
        "再現するものではありません。公表係数の丸めにより、接続点の微小な差を設計上の不連続と断定できない",
        "場合があります。",
        "",
        "この版では Apple Log と DJI D-Log (native EI) も同じレジストリから自動生成しています。",
    ]: txt.textLine(line)
    cpdf.drawText(txt); page_no(page); cpdf.showPage(); page += 1

    header("Overview - 全カーブ比較")
    overview = [
        ("camera_log_curves_scene_linear.png", "scene-linear: curve"), ("camera_log_first_derivative_scene_linear.png", "scene-linear: first derivative"),
        ("camera_log_second_derivative_scene_linear.png", "scene-linear: second derivative"), ("camera_log_curves_stops.png", "stop domain: curve"),
        ("camera_log_first_derivative_stops.png", "stop domain: first derivative"), ("camera_log_second_derivative_stops.png", "stop domain: second derivative"),
    ]
    mx, top, gapx, gapy = 24, ph-50, 10, 8; cols, rows = 2, 3
    cw = (pw-2*mx-gapx)/cols; ch = (ph-70-gapy*(rows-1))/rows
    for idx, (fn, cap) in enumerate(overview):
        rr, col = divmod(idx, cols); x0 = mx + col*(cw+gapx); y0 = top-(rr+1)*ch-rr*gapy
        img = ImageReader(str(FIG_OV/fn)); iw, ih = img.getSize(); scale = min(cw/iw, (ch-12)/ih); dw, dh = iw*scale, ih*scale
        cpdf.drawImage(img, x0+(cw-dw)/2, y0+12+(ch-12-dh)/2, dw, dh, preserveAspectRatio=True, mask="auto")
        cpdf.setFont(font, 7.3); cpdf.drawCentredString(x0+cw/2, y0+2, cap)
    page_no(page); cpdf.showPage(); page += 1

    for i in range(0, len(CAMERAS), 2):
        names = CAMERAS[i:i+2]; header("Individual curve contact sheets")
        ah = ph-64; card_h=(ah-10)/2
        for k, curve in enumerate(names):
            img = ImageReader(str(individual_assets[curve["id"]])); iw, ih = img.getSize(); x0=28; y0=ph-55-(k+1)*card_h-k*10; maxw=pw-56; maxh=card_h-4
            scale=min(maxw/iw,maxh/ih); dw,dh=iw*scale,ih*scale
            cpdf.drawImage(img,x0+(maxw-dw)/2,y0+(maxh-dh)/2,dw,dh,preserveAspectRatio=True,mask="auto")
        page_no(page); cpdf.showPage(); page += 1

    header("参考文献 / implementation sources", "数式を拾った公開文書。完全なURLは companion QMD / references.bib に収録。")
    y=ph-70
    used=[]
    for curve in CURVES:
        for key in curve.get("sources", []):
            if key not in used: used.append(key)
    for key in used:
        s=SOURCES[key]; line=f"{s.get('organization', s.get('author',''))}: {s['title']} ({s.get('year','')})"
        cpdf.setFont(font, 7.6); cpdf.drawString(34,y,line[:145]); y-=16
        if y<32: page_no(page); cpdf.showPage(); page+=1; header("参考文献 / implementation sources (cont.)"); y=ph-65
    page_no(page); cpdf.save()
    return pdf_path


def resolve_includes(text):
    pat = re.compile(r"\{\{<\s*include\s+([^\s>]+)\s*>\}\}")
    def repl(m):
        p = ROOT / m.group(1)
        return p.read_text(encoding="utf-8")
    prev = None
    while prev != text:
        prev = text; text = pat.sub(repl, text)
    return text


def render_index():
    # styles.css is intentionally renderer-independent: the build may use bare Pandoc.
    src = (ROOT / "article.qmd").read_text(encoding="utf-8")
    merged = resolve_includes(src)
    temp = ROOT / ".article_resolved.qmd"
    temp.write_text(merged, encoding="utf-8")
    if shutil.which("pandoc"):
        cmd = [
            "pandoc", str(temp), "-f", "markdown", "-t", "html5", "--standalone", "--toc", "--number-sections",
            "--citeproc", "--bibliography", str(ROOT/"references.bib"), "--css", "styles.css",
            "--mathjax=https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js", "-o", str(ROOT/"index.html")
        ]
        subprocess.run(cmd, cwd=ROOT, check=True)
        temp.unlink(missing_ok=True)
    elif shutil.which("quarto"):
        temp.unlink(missing_ok=True)
        subprocess.run(["quarto", "render", "article.qmd"], cwd=ROOT, check=True)
    else:
        temp.unlink(missing_ok=True)
        raise RuntimeError("Neither pandoc nor quarto was found. Install one to render index.html.")


def update_files_manifest():
    files = []
    for p in sorted(ROOT.rglob("*")):
        if p.is_file() and ".git" not in p.parts and p.name not in {"FILES.txt"}:
            files.append(str(p.relative_to(ROOT)).replace("\\", "/"))
    (ROOT / "FILES.txt").write_text("\n".join(files) + "\n", encoding="utf-8")


def write_build_metadata():
    meta = {
        "registry_version": 1,
        "camera_curve_count": len(CAMERAS),
        "reference_curve_count": len(REFERENCES),
        "camera_curve_ids": [c["id"] for c in CAMERAS],
        "single_source_of_truth": ["curve_specs/curves.yaml", "curve_specs/sources.yaml", "scripts/curve_models.py"],
    }
    (DATA / "build_manifest.json").write_text(json.dumps(meta, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def main():
    clean_generated_assets(); generate_bib()
    for fn, dom, met in [
        ("camera_log_curves_scene_linear", "scene", "y"), ("camera_log_first_derivative_scene_linear", "scene", "d1"), ("camera_log_second_derivative_scene_linear", "scene", "d2"),
        ("camera_log_curves_stops", "stop", "y"), ("camera_log_first_derivative_stops", "stop", "d1"), ("camera_log_second_derivative_stops", "stop", "d2"),
    ]: save_overview_plot(fn, dom, met)
    save_reference_plots()
    summary_df, junction_df = generate_tables(); generate_fragments(summary_df, junction_df)
    build_interactive(); individual_assets = make_individual_assets(); pdf = build_pdf(individual_assets)
    write_build_metadata(); render_index(); update_files_manifest()
    print(f"Built {len(CAMERAS)} camera curves + {len(REFERENCES)} references")
    print("index:", ROOT / "index.html")
    print("compare:", ROOT / "compare.html")
    print("pdf:", pdf)


if __name__ == "__main__":
    main()
